name: calendar
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  cr_calendar:
  easy_search_bar: ^2.5.0
  cupertino_icons: ^1.0.4
  intl: ^0.17.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.0
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.0

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.8
  source_gen: ^1.2.6

flutter:
  uses-material-design: true